services:
  flask:
    build: ./web
    environment:
      - DB_HOST=mariadb
      - DB_USER=flaskuser
      - DB_PASSWORD=flaskpass
      - DB_NAME=flaskdb
    depends_on:
      - mariadb
    volumes:
      - ./web:/app
    ports:
      - "5000:5000"
    networks:
      - gesthub

  mariadb:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=flaskdb
      - MYSQL_USER=flaskuser
      - MYSQL_PASSWORD=flaskpass
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - gesthub

  mongo:
    image: arm64v8/mongo:4.4
    volumes:
      - mongo_data:/data/db
    networks:
      - gesthub

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.5
    command:
      - start-dev
      - --hostname=keycloak.ninolbt.com
      - --hostname-strict=false
      - --hostname-strict-https=false
      - --proxy=edge
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL_HOST=keycloak-db
      - KC_DB_URL_DATABASE=keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloakpass
    ports:
      - "8080:8080"
    depends_on:
      - keycloak-db
    volumes:
      - keycloak_data:/opt/keycloak/data
    networks:
      - gesthub

  keycloak-db:
    image: postgres:13
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloakpass
    volumes:
      - keycloakdb_data:/var/lib/postgresql/data
    networks:
      - gesthub

  # plane:
  #   image: planehq/plane:latest
  #   container_name: plane
  #   depends_on:
  #     - plane-db
  #   environment:
  #     DATABASE_URL: postgres://plane:plane@plane-db:5432/plane
  #     SECRET_KEY: supersecretkeyhere
  #     ENABLE_OPENID_CONNECT: "true"
  #     OIDC_RP_CLIENT_ID: plane-client
  #     OIDC_RP_CLIENT_SECRET: changeme
  #     OIDC_OP_AUTHORIZATION_ENDPOINT: https://keycloak.ninolbt.com/realms/gesthub/protocol/openid-connect/auth
  #     OIDC_OP_TOKEN_ENDPOINT: https://keycloak.ninolbt.com/realms/gesthub/protocol/openid-connect/token
  #     OIDC_OP_USER_ENDPOINT: https://keycloak.ninolbt.com/realms/gesthub/protocol/openid-connect/userinfo
  #     OIDC_OP_JWKS_ENDPOINT: https://keycloak.ninolbt.com/realms/gesthub/protocol/openid-connect/certs
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - gesthub

  # plane-db:
  #   image: postgres:15
  #   container_name: plane-db
  #   environment:
  #     POSTGRES_DB: plane
  #     POSTGRES_USER: plane
  #     POSTGRES_PASSWORD: plane
  #   volumes:
  #     - plane_db_data:/var/lib/postgresql/data
  #   networks:
  #     - gesthub

networks:
  gesthub:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
  mariadb_data:
  mongo_data:
  keycloak_data:
  keycloakdb_data:
  plane_db_data:
